chat:
  local:
    reply: true
    format: "{wdg_chatLoc} {wdg_nick} » {wdg_message}"
    prefix: ""
    plots: true
    radius: 200
  global:
    reply: false
    format: "{wdg_chatGlob} {wdg_nick} » {wdg_message}"
    prefix: "!"
    plots: false
    radius: -1
  staff:
    reply: true
    format: "{wdg_chatStaff} {wdg_nick} » {wdg_message}"
    prefix: "!"
    plots: false
    radius: -1

reply:
  error_msg: "&cК сожалению в данном чате отключены ответы :("
  format:
    - " "
    - "   §8§l§m┏━━§a{reply_nick}§7: {reply_msg}"
    - "{message_component}"

widgets:
  chatLoc:
    text: "&e&lL"
  chatGlob:
    text: "&6&lG"
    actions:
      SUGGEST_COMMAND: "!"
  chatStaff:
    text: "&6&lG"
    actions:
      SUGGEST_COMMAND: "!"
  nick:
    text: "{nick}"
    actions:
      TOOLTIP:
        - "{nick}"
        - "ХП: %player_health_rounded%"
  message:
    text: "{message}"
    actions:
      SUGGEST_COMMAND: "/chat reply {message_id}"
      TOOLTIP:
        - "&7Ответить &b{nick}&7: &f{message}"
cooldown:
  seconds: 10
  messages:
  - "&cPlease wait before sending another message.\nYou can chat again in {time} seconds."
  - "&eSlow down! You're chatting too quickly.\nTake a moment and try again in {time} seconds."
  - "&aYou're on cooldown. Take a breather.\nYou can chat again in {time} seconds."


