name: ExtendedChat
main: me.nitkanikita.extendedchat.Main
version: 1.0
api-version: 1.12
commands:
  exchat:
    description: ExChat
    aliases:
      - extendedChat
      - chat
    usage: /chat
softdepend:
  - PlaceholderAPI
    